/**
 * Regiones y Comunas de Chile
 * 
 * Este archivo contiene todas las regiones de Chile y sus comunas asociadas.
 * Se utiliza en todos los formularios que requieren selección de región y comuna.
 */

export interface RegionOption {
  value: string;
  label: string;
}

export interface ComunaOption {
  value: string;
  label: string;
}

/**
 * Lista de todas las regiones de Chile (de norte a sur)
 */
export const regionesChile: RegionOption[] = [
  { value: "arica", label: "Región de Arica y Parinacota" },
  { value: "tarapaca", label: "Región de Tarapacá" },
  { value: "antofagasta", label: "Región de Antofagasta" },
  { value: "atacama", label: "Región de Atacama" },
  { value: "coquimbo", label: "Región de Coquimbo" },
  { value: "valparaiso", label: "Región de Valparaíso" },
  { value: "metropolitana", label: "Región Metropolitana" },
  { value: "ohiggins", label: "Región del Libertador Gral. Bernardo O'Higgins" },
  { value: "maule", label: "Región del Maule" },
  { value: "nuble", label: "Región de Ñuble" },
  { value: "biobio", label: "Región del Biobío" },
  { value: "araucania", label: "Región de La Araucanía" },
  { value: "rios", label: "Región de Los Ríos" },
  { value: "lagos", label: "Región de Los Lagos" },
  { value: "aysen", label: "Región de Aysén del Gral. Carlos Ibáñez del Campo" },
  { value: "magallanes", label: "Región de Magallanes y de la Antártica Chilena" },
];

/**
 * Comunas agrupadas por región
 * TODAS las 346 comunas de Chile organizadas por región
 */
export const comunasPorRegion: Record<string, ComunaOption[]> = {
  arica: [
    { value: "arica", label: "Arica" },
    { value: "camarones", label: "Camarones" },
    { value: "putre", label: "Putre" },
    { value: "general_lagos", label: "General Lagos" },
  ],
  tarapaca: [
    { value: "iquique", label: "Iquique" },
    { value: "alto_hospicio", label: "Alto Hospicio" },
    { value: "pica", label: "Pica" },
    { value: "pozo_almonte", label: "Pozo Almonte" },
    { value: "camina", label: "Camiña" },
    { value: "colchane", label: "Colchane" },
    { value: "huara", label: "Huara" },
  ],
  antofagasta: [
    { value: "antofagasta", label: "Antofagasta" },
    { value: "calama", label: "Calama" },
    { value: "tocopilla", label: "Tocopilla" },
    { value: "mejillones", label: "Mejillones" },
    { value: "taltal", label: "Taltal" },
    { value: "ollague", label: "Ollagüe" },
    { value: "san_pedro_atacama", label: "San Pedro de Atacama" },
    { value: "sierra_gorda", label: "Sierra Gorda" },
    { value: "maria_elena", label: "María Elena" },
  ],
  atacama: [
    { value: "copiapo", label: "Copiapó" },
    { value: "caldera", label: "Caldera" },
    { value: "chanaral", label: "Chañaral" },
    { value: "vallenar", label: "Vallenar" },
    { value: "diego_almagro", label: "Diego de Almagro" },
    { value: "tierra_amarilla", label: "Tierra Amarilla" },
    { value: "huasco", label: "Huasco" },
    { value: "freirina", label: "Freirina" },
    { value: "alto_del_carmen", label: "Alto del Carmen" },
  ],
  coquimbo: [
    { value: "la_serena", label: "La Serena" },
    { value: "coquimbo", label: "Coquimbo" },
    { value: "ovalle", label: "Ovalle" },
    { value: "illapel", label: "Illapel" },
    { value: "vicuna", label: "Vicuña" },
    { value: "andacollo", label: "Andacollo" },
    { value: "la_higuera", label: "La Higuera" },
    { value: "paihuano", label: "Paihuano" },
    { value: "combarbala", label: "Combarbalá" },
    { value: "monte_patria", label: "Monte Patria" },
    { value: "punitaqui", label: "Punitaqui" },
    { value: "rio_hurtado", label: "Río Hurtado" },
    { value: "salamanca", label: "Salamanca" },
    { value: "canela", label: "Canela" },
    { value: "los_vilos", label: "Los Vilos" },
  ],
  valparaiso: [
    { value: "valparaiso", label: "Valparaíso" },
    { value: "vina_del_mar", label: "Viña del Mar" },
    { value: "quilpue", label: "Quilpué" },
    { value: "villa_alemana", label: "Villa Alemana" },
    { value: "san_antonio", label: "San Antonio" },
    { value: "quillota", label: "Quillota" },
    { value: "los_andes", label: "Los Andes" },
    { value: "casablanca", label: "Casablanca" },
    { value: "concon", label: "Concón" },
    { value: "juan_fernandez", label: "Juan Fernández" },
    { value: "puchuncavi", label: "Puchuncaví" },
    { value: "quintero", label: "Quintero" },
    { value: "algarrobo", label: "Algarrobo" },
    { value: "cartagena", label: "Cartagena" },
    { value: "el_quisco", label: "El Quisco" },
    { value: "el_tabo", label: "El Tabo" },
    { value: "santo_domingo", label: "Santo Domingo" },
    { value: "isla_de_pascua", label: "Isla de Pascua" },
    { value: "calera", label: "Calera" },
    { value: "hijuelas", label: "Hijuelas" },
    { value: "la_cruz", label: "La Cruz" },
    { value: "nogales", label: "Nogales" },
    { value: "limache", label: "Limache" },
    { value: "olmue", label: "Olmué" },
    { value: "cabildo", label: "Cabildo" },
    { value: "la_ligua", label: "La Ligua" },
    { value: "papudo", label: "Papudo" },
    { value: "petorca", label: "Petorca" },
    { value: "zapallar", label: "Zapallar" },
    { value: "calle_larga", label: "Calle Larga" },
    { value: "rinconada", label: "Rinconada" },
    { value: "san_esteban", label: "San Esteban" },
    { value: "catemu", label: "Catemu" },
    { value: "llaillay", label: "Llaillay" },
    { value: "panquehue", label: "Panquehue" },
    { value: "putaendo", label: "Putaendo" },
    { value: "santa_maria", label: "Santa María" },
  ],
  metropolitana: [
    { value: "santiago", label: "Santiago" },
    { value: "cerrillos", label: "Cerrillos" },
    { value: "cerro_navia", label: "Cerro Navia" },
    { value: "conchali", label: "Conchalí" },
    { value: "el_bosque", label: "El Bosque" },
    { value: "estacion_central", label: "Estación Central" },
    { value: "huechuraba", label: "Huechuraba" },
    { value: "independencia", label: "Independencia" },
    { value: "la_cisterna", label: "La Cisterna" },
    { value: "la_florida", label: "La Florida" },
    { value: "la_granja", label: "La Granja" },
    { value: "la_pintana", label: "La Pintana" },
    { value: "la_reina", label: "La Reina" },
    { value: "las_condes", label: "Las Condes" },
    { value: "lo_barnechea", label: "Lo Barnechea" },
    { value: "lo_espejo", label: "Lo Espejo" },
    { value: "lo_prado", label: "Lo Prado" },
    { value: "macul", label: "Macul" },
    { value: "maipu", label: "Maipú" },
    { value: "nunoa", label: "Ñuñoa" },
    { value: "pedro_aguirre_cerda", label: "Pedro Aguirre Cerda" },
    { value: "penalolen", label: "Peñalolén" },
    { value: "providencia", label: "Providencia" },
    { value: "pudahuel", label: "Pudahuel" },
    { value: "quilicura", label: "Quilicura" },
    { value: "quinta_normal", label: "Quinta Normal" },
    { value: "recoleta", label: "Recoleta" },
    { value: "renca", label: "Renca" },
    { value: "san_joaquin", label: "San Joaquín" },
    { value: "san_miguel", label: "San Miguel" },
    { value: "san_ramon", label: "San Ramón" },
    { value: "vitacura", label: "Vitacura" },
    { value: "puente_alto", label: "Puente Alto" },
    { value: "pirque", label: "Pirque" },
    { value: "san_jose_maipo", label: "San José de Maipo" },
    { value: "colina", label: "Colina" },
    { value: "lampa", label: "Lampa" },
    { value: "tiltil", label: "Tiltil" },
    { value: "san_bernardo", label: "San Bernardo" },
    { value: "buin", label: "Buin" },
    { value: "calera_tango", label: "Calera de Tango" },
    { value: "paine", label: "Paine" },
    { value: "melipilla", label: "Melipilla" },
    { value: "alhue", label: "Alhué" },
    { value: "curacavi", label: "Curacaví" },
    { value: "maria_pinto", label: "María Pinto" },
    { value: "san_pedro", label: "San Pedro" },
    { value: "talagante", label: "Talagante" },
    { value: "el_monte", label: "El Monte" },
    { value: "isla_maipo", label: "Isla de Maipo" },
    { value: "padre_hurtado", label: "Padre Hurtado" },
    { value: "penaflor", label: "Peñaflor" },
  ],
  ohiggins: [
    { value: "rancagua", label: "Rancagua" },
    { value: "codegua", label: "Codegua" },
    { value: "coinco", label: "Coinco" },
    { value: "coltauco", label: "Coltauco" },
    { value: "donihue", label: "Doñihue" },
    { value: "graneros", label: "Graneros" },
    { value: "las_cabras", label: "Las Cabras" },
    { value: "machal", label: "Machalí" },
    { value: "malloa", label: "Malloa" },
    { value: "mostazal", label: "Mostazal" },
    { value: "olivar", label: "Olivar" },
    { value: "peumo", label: "Peumo" },
    { value: "pichidegua", label: "Pichidegua" },
    { value: "quinta_tilcoco", label: "Quinta de Tilcoco" },
    { value: "rengo", label: "Rengo" },
    { value: "requinoa", label: "Requínoa" },
    { value: "san_vicente", label: "San Vicente" },
    { value: "pichilemu", label: "Pichilemu" },
    { value: "la_estrella", label: "La Estrella" },
    { value: "litueche", label: "Litueche" },
    { value: "marchihue", label: "Marchihue" },
    { value: "navidad", label: "Navidad" },
    { value: "paredones", label: "Paredones" },
    { value: "san_fernando", label: "San Fernando" },
    { value: "chepica", label: "Chépica" },
    { value: "chimbarongo", label: "Chimbarongo" },
    { value: "lolol", label: "Lolol" },
    { value: "nancagua", label: "Nancagua" },
    { value: "palmilla", label: "Palmilla" },
    { value: "peralillo", label: "Peralillo" },
    { value: "placilla", label: "Placilla" },
    { value: "pumanque", label: "Pumanque" },
    { value: "santa_cruz", label: "Santa Cruz" },
  ],
  maule: [
    { value: "talca", label: "Talca" },
    { value: "constitucion", label: "Constitución" },
    { value: "curepto", label: "Curepto" },
    { value: "empedrado", label: "Empedrado" },
    { value: "maule", label: "Maule" },
    { value: "pelarco", label: "Pelarco" },
    { value: "pencahue", label: "Pencahue" },
    { value: "rio_claro", label: "Río Claro" },
    { value: "san_clemente", label: "San Clemente" },
    { value: "san_rafael", label: "San Rafael" },
    { value: "curico", label: "Curicó" },
    { value: "hualane", label: "Hualañé" },
    { value: "licanten", label: "Licantén" },
    { value: "molina", label: "Molina" },
    { value: "rauco", label: "Rauco" },
    { value: "romeral", label: "Romeral" },
    { value: "sagrada_familia", label: "Sagrada Familia" },
    { value: "teno", label: "Teno" },
    { value: "vichuquen", label: "Vichuquén" },
    { value: "linares", label: "Linares" },
    { value: "colbun", label: "Colbún" },
    { value: "longavi", label: "Longaví" },
    { value: "parral", label: "Parral" },
    { value: "retiro", label: "Retiro" },
    { value: "san_javier", label: "San Javier" },
    { value: "villa_alegre", label: "Villa Alegre" },
    { value: "yerbas_buenas", label: "Yerbas Buenas" },
    { value: "cauquenes", label: "Cauquenes" },
    { value: "chanco", label: "Chanco" },
    { value: "pelluhue", label: "Pelluhue" },
  ],
  nuble: [
    { value: "chillan", label: "Chillán" },
    { value: "bulnes", label: "Bulnes" },
    { value: "chillan_viejo", label: "Chillán Viejo" },
    { value: "el_carmen", label: "El Carmen" },
    { value: "pemuco", label: "Pemuco" },
    { value: "pinto", label: "Pinto" },
    { value: "quillon", label: "Quillón" },
    { value: "san_ignacio", label: "San Ignacio" },
    { value: "yungay", label: "Yungay" },
    { value: "cobquecura", label: "Cobquecura" },
    { value: "coelemu", label: "Coelemu" },
    { value: "ninhue", label: "Ninhue" },
    { value: "portezuelo", label: "Portezuelo" },
    { value: "quirihue", label: "Quirihue" },
    { value: "ranquil", label: "Ránquil" },
    { value: "trehuaco", label: "Treguaco" },
    { value: "cobquecura", label: "Cobquecura" },
    { value: "coihueco", label: "Coihueco" },
    { value: "niquen", label: "Ñiquén" },
    { value: "san_carlos", label: "San Carlos" },
    { value: "san_fabian", label: "San Fabián" },
    { value: "san_nicolas", label: "San Nicolás" },
  ],
  biobio: [
    { value: "concepcion", label: "Concepción" },
    { value: "coronel", label: "Coronel" },
    { value: "chiguayante", label: "Chiguayante" },
    { value: "florida", label: "Florida" },
    { value: "hualqui", label: "Hualqui" },
    { value: "lota", label: "Lota" },
    { value: "penco", label: "Penco" },
    { value: "san_pedro_paz", label: "San Pedro de la Paz" },
    { value: "santa_juana", label: "Santa Juana" },
    { value: "talcahuano", label: "Talcahuano" },
    { value: "tome", label: "Tomé" },
    { value: "hualpen", label: "Hualpén" },
    { value: "lebu", label: "Lebu" },
    { value: "arauco", label: "Arauco" },
    { value: "canete", label: "Cañete" },
    { value: "contulmo", label: "Contulmo" },
    { value: "curanilahue", label: "Curanilahue" },
    { value: "los_alamos", label: "Los Álamos" },
    { value: "tirua", label: "Tirúa" },
    { value: "los_angeles", label: "Los Ángeles" },
    { value: "antuco", label: "Antuco" },
    { value: "cabrero", label: "Cabrero" },
    { value: "laja", label: "Laja" },
    { value: "mulchen", label: "Mulchén" },
    { value: "nacimiento", label: "Nacimiento" },
    { value: "negrete", label: "Negrete" },
    { value: "quilaco", label: "Quilaco" },
    { value: "quilleco", label: "Quilleco" },
    { value: "san_rosendo", label: "San Rosendo" },
    { value: "santa_barbara", label: "Santa Bárbara" },
    { value: "tucapel", label: "Tucapel" },
    { value: "yumbel", label: "Yumbel" },
    { value: "alto_biobio", label: "Alto Biobío" },
  ],
  araucania: [
    { value: "temuco", label: "Temuco" },
    { value: "carahue", label: "Carahue" },
    { value: "cunco", label: "Cunco" },
    { value: "curarrehue", label: "Curarrehue" },
    { value: "freire", label: "Freire" },
    { value: "galvarino", label: "Galvarino" },
    { value: "gorbea", label: "Gorbea" },
    { value: "lautaro", label: "Lautaro" },
    { value: "loncoche", label: "Loncoche" },
    { value: "melipeuco", label: "Melipeuco" },
    { value: "nueva_imperial", label: "Nueva Imperial" },
    { value: "padre_las_casas", label: "Padre Las Casas" },
    { value: "perquenco", label: "Perquenco" },
    { value: "pitrufquen", label: "Pitrufquén" },
    { value: "pucon", label: "Pucón" },
    { value: "saavedra", label: "Saavedra" },
    { value: "teodoro_schmidt", label: "Teodoro Schmidt" },
    { value: "tolten", label: "Toltén" },
    { value: "vilcun", label: "Vilcún" },
    { value: "villarrica", label: "Villarrica" },
    { value: "cholchol", label: "Cholchol" },
    { value: "angol", label: "Angol" },
    { value: "collipulli", label: "Collipulli" },
    { value: "curacautin", label: "Curacautín" },
    { value: "ercilla", label: "Ercilla" },
    { value: "lonquimay", label: "Lonquimay" },
    { value: "los_sauces", label: "Los Sauces" },
    { value: "lumaco", label: "Lumaco" },
    { value: "puren", label: "Purén" },
    { value: "renaico", label: "Renaico" },
    { value: "traiguen", label: "Traiguén" },
    { value: "victoria", label: "Victoria" },
  ],
  rios: [
    { value: "valdivia", label: "Valdivia" },
    { value: "corral", label: "Corral" },
    { value: "lanco", label: "Lanco" },
    { value: "los_lagos", label: "Los Lagos" },
    { value: "mafil", label: "Máfil" },
    { value: "mariquina", label: "Mariquina" },
    { value: "paillaco", label: "Paillaco" },
    { value: "panguipulli", label: "Panguipulli" },
    { value: "la_union", label: "La Unión" },
    { value: "futrono", label: "Futrono" },
    { value: "lago_ranco", label: "Lago Ranco" },
    { value: "rio_bueno", label: "Río Bueno" },
  ],
  lagos: [
    { value: "puerto_montt", label: "Puerto Montt" },
    { value: "calbuco", label: "Calbuco" },
    { value: "cochamo", label: "Cochamó" },
    { value: "fresia", label: "Fresia" },
    { value: "frutillar", label: "Frutillar" },
    { value: "los_muermos", label: "Los Muermos" },
    { value: "llanquihue", label: "Llanquihue" },
    { value: "maullin", label: "Maullín" },
    { value: "puerto_varas", label: "Puerto Varas" },
    { value: "castro", label: "Castro" },
    { value: "ancud", label: "Ancud" },
    { value: "chonchi", label: "Chonchi" },
    { value: "curaco_velez", label: "Curaco de Vélez" },
    { value: "dalcahue", label: "Dalcahue" },
    { value: "puqueldon", label: "Puqueldón" },
    { value: "queilen", label: "Queilén" },
    { value: "quellon", label: "Quellón" },
    { value: "quemchi", label: "Quemchi" },
    { value: "quinchao", label: "Quinchao" },
    { value: "osorno", label: "Osorno" },
    { value: "puerto_octay", label: "Puerto Octay" },
    { value: "purranque", label: "Purranque" },
    { value: "puyehue", label: "Puyehue" },
    { value: "rio_negro", label: "Río Negro" },
    { value: "san_juan_costa", label: "San Juan de la Costa" },
    { value: "san_pablo", label: "San Pablo" },
    { value: "chaiten", label: "Chaitén" },
    { value: "futaleufu", label: "Futaleufú" },
    { value: "hualaihue", label: "Hualaihué" },
    { value: "palena", label: "Palena" },
  ],
  aysen: [
    { value: "coyhaique", label: "Coyhaique" },
    { value: "lago_verde", label: "Lago Verde" },
    { value: "aysen", label: "Aysén" },
    { value: "cisnes", label: "Cisnes" },
    { value: "guaitecas", label: "Guaitecas" },
    { value: "cochrane", label: "Cochrane" },
    { value: "ohiggins", label: "O'Higgins" },
    { value: "tortel", label: "Tortel" },
    { value: "chile_chico", label: "Chile Chico" },
    { value: "rio_ibanez", label: "Río Ibáñez" },
  ],
  magallanes: [
    { value: "punta_arenas", label: "Punta Arenas" },
    { value: "laguna_blanca", label: "Laguna Blanca" },
    { value: "rio_verde", label: "Río Verde" },
    { value: "san_gregorio", label: "San Gregorio" },
    { value: "cabo_hornos", label: "Cabo de Hornos" },
    { value: "antartica", label: "Antártica" },
    { value: "porvenir", label: "Porvenir" },
    { value: "primavera", label: "Primavera" },
    { value: "timaukel", label: "Timaukel" },
    { value: "puerto_natales", label: "Puerto Natales" },
    { value: "torres_paine", label: "Torres del Paine" },
  ],
};

/**
 * Obtiene las comunas de una región específica
 * @param regionValue - El valor de la región
 * @returns Array de comunas o array vacío si no existe la región
 */
export const getComunasByRegion = (regionValue: string): ComunaOption[] => {
  return comunasPorRegion[regionValue] || [];
};
